apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: IMAGE
    value: maistra/istio-operator-centos7:0.10.0
  - name: PULL_POLICY
    value: Always
  - name: NAMESPACE
    value: istio-operator
  - name: RELEASE
    value: v3.10
  - name: MASTER_PUBLIC_URL
    value: https://127.0.0.1:8443
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: istio-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: istio-operator
  - apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: controlplanes.istio.openshift.com
    spec:
      group: istio.openshift.com
      names:
        kind: ControlPlane
        listKind: ControlPlaneList
        plural: controlplanes
        singular: controlplane
      scope: Namespaced
      subresources:
        status: {}
      version: v1alpha3
  - apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: installations.istio.openshift.com
      labels:
        name: istio-operator
    spec:
      group: istio.openshift.com
      names:
        kind: Installation
        plural: installations
        singular: installation
      scope: Namespaced
      subresources:
        status: {}
      version: v1alpha1

  - apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      name: elasticsearch-sysctl
    spec:
      template:
        metadata:
          labels:
            name: elasticsearch-sysctl
        spec:
          containers:
            - name: elasticsearch-sysctl
              image: ${IMAGE}
              imagePullPolicy: ${PULL_POLICY}
              securityContext:
                privileged: true
                runAsUser: 0
              restartPolicy: Always
              command:
                - "bash"
              args:
                - "-c"
                - 'while : ; do current=$(sysctl -n vm.max_map_count) ; if [ "${current}" -lt 262144 ] ; then echo "$(date): Current vm.max_map_count setting is ${current}, updating to 262144 for Elasticsearch" ; sysctl vm.max_map_count=262144 ; fi; sleep 60 ; done'

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: istio-operator
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: istio-operator
      template:
        metadata:
          labels:
            name: istio-operator
        spec:
          serviceAccountName: istio-operator
          volumes:
            - name: discovery-cache
              emptyDir:
                medium: Memory
          containers:
            - name: istio-operator
              image: ${IMAGE}
              ports:
                - containerPort: 60000
                  name: metrics
              command:
                - istio-operator
                - --discoveryCacheDir
                - /home/istio-operator/.kube/cache/discovery
              imagePullPolicy: Always
              env:
                - name: WATCH_NAMESPACE
                  value: istio-system
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                    fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: "istio-operator"
              volumeMounts:
                - name: discovery-cache
                  mountPath: /home/istio-operator/.kube/cache/discovery
